project '../project.xcodeproj'
source 'https://github.com/CocoaPods/Specs.git'
target 'project' do
pod 'SwiftKeychainWrapper'
pod 'GoogleMaps'
pod 'GooglePlaces'
pod 'Alamofire'
pod 'Firebase/Core'
pod 'VVWaterWaveView'
pod 'FacebookCore'
pod 'FacebookLogin'
pod 'FacebookShare'
use_frameworks!
end
